import alphabets

CONFIGS = {
    'infor_chip': {
        'arch': 'res_18',
        'heads': {'hm': 8, 'wh': 2, 'reg': 2},
        'head_conv': 64,
        'device': 'cpu',
        'load_model': '/home/dtvingg/Desktop/Doan_20241/code/20204705_DaoTuongVinh_20241/weight/weight_infor_cccd_chip.pth',
        'mean': [0.472459, 0.47508, 0.482652],
        'std': [0.255084, 0.254665, 0.257073],
        'num_classes': 8,
        'test_scales': [1.0],
        'fix_res': True,
        'input_h': 512,
        'input_w': 512,
        'pad': 31,
        'flip_test': False,
        'down_ratio': 4,
        'dataset': 'infor',
        'debug': 0,
        'debugger_theme': 'white',
        'gpus': [0],
        'reg_offset': True,
        'not_reg_offset': False,
        'cat_spec_wh': False,
        'K': 100,
        'nms': False,
        'label': ['id', 'hoten', 'ngaysinh', 'gioitinh', 'quoctich', 'quequan', 'diachi', 'giatriden']
    },
    'infor_2024': {
        'arch': 'res_18',
        'heads': {'hm': 5, 'wh': 2, 'reg': 2},
        'head_conv': 64,
        'device': 'cpu',
        'load_model': '/home/dtvingg/Desktop/Doan_20241/code/20204705_DaoTuongVinh_20241/weight/weight_infor_cccd_2024.pth',
        'mean': [0.472459, 0.47508, 0.482652],
        'std': [0.255084, 0.254665, 0.257073],
        'num_classes': 5,
        'test_scales': [1.0],
        'fix_res': True,
        'input_h': 512,
        'input_w': 512,
        'pad': 31,
        'flip_test': False,
        'down_ratio': 4,
        'dataset': 'infor',
        'debug': 0,
        'debugger_theme': 'white',
        'gpus': [0],
        'reg_offset': True,
        'not_reg_offset': False,
        'cat_spec_wh': False,
        'K': 100,
        'nms': False,
        'label': ['id', 'hoten', 'ngaysinh', 'gioitinh', 'quoctich']
    },
    'crnn_chu':{
        'alphabet' : alphabets.alphabet_chu,
        'keep_ratio' : False,
        'manualSeed' : 1234,
        'random_sample' : True,
        'imgH' : 32,
        'imgW' : 100,
        'nh' : 256,
        'nc' : 1,
        'weight' : 'weight/CRNN_100_400k.pth',
        'expr_dir' : 'expr',
        'dealwith_lossnan' : False,
        'cuda' : True,
        'multi_gpu' : False,
        'ngpu' : 1 ,
        'workers' : 0,
        'device': 'cpu'
    },
    'crnn_so':{
        'alphabet' : alphabets.alphabet_so,
        'keep_ratio' : False,
        'manualSeed' : 1234,
        'random_sample' : True,
        'imgH' : 32,
        'imgW' : 100,
        'nh' : 256,
        'nc' : 1,
        'weight' : 'weight/CRNN_100_so_30k.pth',
        'expr_dir' : 'expr',
        'dealwith_lossnan' : False,
        'cuda' : True,
        'multi_gpu' : False,
        'ngpu' : 1 ,
        'workers' : 0,
        'device': 'cpu'
    }
}

def get_config(name):
    return CONFIGS.get(name, None)